### PR TITLE
feat(actions): added semantic PR check workflow. Fixes #47

### LINKED ISSUE #47: Establish project governance, use good practices.

### PR DESCRIPTION
**Pull request by rohankmr414**
Signed-off-by: Rohan Kumar <rohankmr414@gmail.com>

Fixes #47

### CODE REVIEW

**Comment by rohankmr414** [comment]
@halcyondude can you disable the approval requirement for running action workflows for outside forks?

**Review by kenfinnigan — APPROVED** [review]

**Comment by rohankmr414** [comment]
still requires approval

**Comment by halcyondude** [comment]
hrm...just re-saved this...

image

**Comment by halcyondude** [comment]
at this point AFAIK you shouldn't need another approval, just the first time.

**Comment by halcyondude** [comment]
This is pretty cool!  TIL :)

https://www.conventionalcommits.org/en/v1.0.0/

```
<type>[optional scope]: <description>

[optional body]

[optional footer(s)]
```

## Available types:
 - feat: A new feature
 - fix: A bug fix
 - docs: Documentation only changes
 - style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
 - refactor: A code change that neither fixes a bug nor adds a feature
 - perf: A code change that improves performance
 - test: Adding missing tests or correcting existing tests
 - build: Changes that affect the build system or external dependencies (example scopes: gulp, broccoli, npm)
 - ci: Changes to our CI configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)
 - chore: Other changes that don't modify src or test files
 - revert: Reverts a previous commit

**Comment by rohankmr414** [comment]
looks ready to merge I guess?

**Comment by halcyondude** [comment]
@rohankmr414 afaik after this merges, new PR's from you shouldn't cause more approvals.  

Thanks for your contribution!  This one makes all manner of sense :)

**Pull request merged**
